#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmake -j 10  $targetType phaseSystems
wmake -j 10 $targetType interfacialModels
wmake -j 10 $targetType interfacialCompositionModels
wmake -j 10 $targetType multiphaseCompressibleMomentumTransportModels
wmake $targetType multiphaseReactions
multiphaseEulerFoam/Allwmake $targetType $*
wmake -j 10 $targetType functionObjects

#------------------------------------------------------------------------------
