// IOdictionary Idict
// (
//     IOobject
//     (
//         "interphaseMassExchangeDict",
//         runTime.constant(),
//         mesh
//         IOobject::MUST_READ_IF_MODIFIED,
//         IOobject::NO_WRITE,
//     )
// );

// wordList speciesToExchange(Idict.lookup("speciesToExchange"));

// word SherwoodNumberModel(Idict.lookup("SherwoodNumberModel"));

// PtrList<volScalarField> mtcList(speciesToExchange.size());



